title: Lucas Makinen's Research Blog
description: For project updates and public code
permalink: /blog/:year/:month/:day/:title
plugins: jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
